(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
shapesData={"shape1":[[0,0,138,0,388,38],[0,0,110,0,311,31],[0,0,88,0,249,25],[],[]],"shape3":[[0,388,179,0,0,231],[0,311,144,0,0,184],[0,249,115,0,0,147],[],[]],"shape2":[[],[0,1,39],[0,1,32],[],[]]};!function(){if("Promise"in window){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},f=function(e){return e.target.closest("a")},p=function(t){var r=t.relatedTarget;r&&f(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},l={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=f(e);c(r)&&u(r.href)},l),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=f(r);c(n)&&(n.addEventListener("mouseout",p,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},l)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.js4 .slider-for .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-2400.jpg':'images/none-1200.jpg');
var e=document.querySelector('.js4 .slider-nav .slide0');e.setAttribute('src',(dpi>1)?'images/thumb-none-722.jpg':'images/thumb-none-361.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-2400-1.jpg':'images/none-1200-1.jpg');
var e=document.querySelector('.js4 .slider-nav .slide1');e.setAttribute('src',(dpi>1)?'images/thumb-none-722-1.jpg':'images/thumb-none-361-1.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-2400-2.jpg':'images/none-1200-2.jpg');
var e=document.querySelector('.js4 .slider-nav .slide2');e.setAttribute('src',(dpi>1)?'images/thumb-none-722-2.jpg':'images/thumb-none-361-2.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-2400-3.jpg':'images/none-1200-3.jpg');
var e=document.querySelector('.js4 .slider-nav .slide3');e.setAttribute('src',(dpi>1)?'images/thumb-none-722-3.jpg':'images/thumb-none-361-3.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-2400-4.jpg':'images/none-1200-4.jpg');
var e=document.querySelector('.js4 .slider-nav .slide4');e.setAttribute('src',(dpi>1)?'images/thumb-none-722-4.jpg':'images/thumb-none-361-4.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/world_map_black-white-668.png':'images/world_map_black-white-334.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?'images/ic_location_on_white_48pt_3x-68.png':'images/ic_location_on_white_48pt_3x-34.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/pasted-image-1174.png':'images/pasted-image-587.png');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.js4 .slider-for .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1920.jpg':'images/none-960-1.jpg');
var e=document.querySelector('.js4 .slider-nav .slide0');e.setAttribute('src',(dpi>1)?'images/thumb-none-562.jpg':'images/thumb-none-281.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1920-1.jpg':'images/none-960-3.jpg');
var e=document.querySelector('.js4 .slider-nav .slide1');e.setAttribute('src',(dpi>1)?'images/thumb-none-562-1.jpg':'images/thumb-none-281-1.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1920-2.jpg':'images/none-960-5.jpg');
var e=document.querySelector('.js4 .slider-nav .slide2');e.setAttribute('src',(dpi>1)?'images/thumb-none-562-2.jpg':'images/thumb-none-281-2.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1920-3.jpg':'images/none-960-7.jpg');
var e=document.querySelector('.js4 .slider-nav .slide3');e.setAttribute('src',(dpi>1)?'images/thumb-none-562-3.jpg':'images/thumb-none-281-3.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1920-4.jpg':'images/none-960-9.jpg');
var e=document.querySelector('.js4 .slider-nav .slide4');e.setAttribute('src',(dpi>1)?'images/thumb-none-562-4.jpg':'images/thumb-none-281-4.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/world_map_black-white-534.png':'images/world_map_black-white-267.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?'images/ic_location_on_white_48pt_3x-54-1.png':'images/ic_location_on_white_48pt_3x-27-1.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/pasted-image-940.png':'images/pasted-image-470.png');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.js4 .slider-for .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536.jpg':'images/none-768.jpg');
var e=document.querySelector('.js4 .slider-nav .slide0');e.setAttribute('src',(dpi>1)?'images/thumb-none-434.jpg':'images/thumb-none-217.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-1.jpg':'images/none-768-1.jpg');
var e=document.querySelector('.js4 .slider-nav .slide1');e.setAttribute('src',(dpi>1)?'images/thumb-none-434-1.jpg':'images/thumb-none-217-1.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-2.jpg':'images/none-768-2.jpg');
var e=document.querySelector('.js4 .slider-nav .slide2');e.setAttribute('src',(dpi>1)?'images/thumb-none-434-2.jpg':'images/thumb-none-217-2.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-3.jpg':'images/none-768-3.jpg');
var e=document.querySelector('.js4 .slider-nav .slide3');e.setAttribute('src',(dpi>1)?'images/thumb-none-434-3.jpg':'images/thumb-none-217-3.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-1536-4.jpg':'images/none-768-4.jpg');
var e=document.querySelector('.js4 .slider-nav .slide4');e.setAttribute('src',(dpi>1)?'images/thumb-none-434-4.jpg':'images/thumb-none-217-4.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/world_map_black-white-426.png':'images/world_map_black-white-213.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?'images/ic_location_on_white_48pt_3x-42.png':'images/ic_location_on_white_48pt_3x-21.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/pasted-image-752.png':'images/pasted-image-376.png');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.js4 .slider-for .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960.jpg':'images/none-480.jpg');
var e=document.querySelector('.js4 .slider-nav .slide0');e.setAttribute('src',(dpi>1)?'images/thumb-none-242.jpg':'images/thumb-none-121.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-2.jpg':'images/none-480-1.jpg');
var e=document.querySelector('.js4 .slider-nav .slide1');e.setAttribute('src',(dpi>1)?'images/thumb-none-242-1.jpg':'images/thumb-none-121-1.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-4.jpg':'images/none-480-2.jpg');
var e=document.querySelector('.js4 .slider-nav .slide2');e.setAttribute('src',(dpi>1)?'images/thumb-none-242-2.jpg':'images/thumb-none-121-2.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-6.jpg':'images/none-480-3.jpg');
var e=document.querySelector('.js4 .slider-nav .slide3');e.setAttribute('src',(dpi>1)?'images/thumb-none-242-3.jpg':'images/thumb-none-121-3.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-960-8.jpg':'images/none-480-4.jpg');
var e=document.querySelector('.js4 .slider-nav .slide4');e.setAttribute('src',(dpi>1)?'images/thumb-none-242-4.jpg':'images/thumb-none-121-4.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/world_map_black-white-566.png':'images/world_map_black-white-283.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?'images/ic_location_on_white_48pt_3x-54.png':'images/ic_location_on_white_48pt_3x-27.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/pasted-image-952.png':'images/pasted-image-476.png');}else{var a='data-src';var e=document.querySelector('.js4 .slider-for .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640.jpg':'images/none-320.jpg');
var e=document.querySelector('.js4 .slider-nav .slide0');e.setAttribute('src',(dpi>1)?'images/thumb-none-136.jpg':'images/thumb-none-68.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-1.jpg':'images/none-320-1.jpg');
var e=document.querySelector('.js4 .slider-nav .slide1');e.setAttribute('src',(dpi>1)?'images/thumb-none-136-1.jpg':'images/thumb-none-68-1.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-2.jpg':'images/none-320-2.jpg');
var e=document.querySelector('.js4 .slider-nav .slide2');e.setAttribute('src',(dpi>1)?'images/thumb-none-136-2.jpg':'images/thumb-none-68-2.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-3.jpg':'images/none-320-3.jpg');
var e=document.querySelector('.js4 .slider-nav .slide3');e.setAttribute('src',(dpi>1)?'images/thumb-none-136-3.jpg':'images/thumb-none-68-3.jpg');
var a='data-src';var e=document.querySelector('.js4 .slider-for .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/none-640-4.jpg':'images/none-320-4.jpg');
var e=document.querySelector('.js4 .slider-nav .slide4');e.setAttribute('src',(dpi>1)?'images/thumb-none-136-4.jpg':'images/thumb-none-68-4.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/world_map_black-white-378.png':'images/world_map_black-white-189.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?'images/ic_location_on_white_48pt_3x-36.png':'images/ic_location_on_white_48pt_3x-18.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/pasted-image-634.png':'images/pasted-image-317.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
initMenu($('#m1')[0]);
$('.js4 .slider-for').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,arrows: false,fade: true,infinite: true,asNavFor: '.js4 .slider-nav',speed: 1200,overflow: 'hidden'});$('.js4 .slider-nav').slick({slidesToShow: 3,slidesToScroll: 1,asNavFor: '.js4 .slider-for',centerMode: true,focusOnSelect: true,speed: 1200,dots: false,arrows: false,infinite: true,autoplay: true,pauseOnHover: false,autoplaySpeed: 5000});var s=new Shapes();window.onresize=function(){s.update();};s.update();
});